# This file contains templated variables to avoid repeating the same hard-coded values.
# Templated variables are denoted by the dollar curly braces token. The following details each templated variable that you can use:
# `default_postfix`: This is a string sourced from the variable `default_postfix`. This can be used to append to resource names for consistency.
# `default_location`: This is an Azure location sourced from the `default_location` variable. This can be used to set the location of resources.
# `root_management_group_id`: This is ID of the top level managemrnt group that you will build your hierarchy under. This is primarily used to set the root management group `parent`.
# `subscription_id_identity`: The subscription ID of the subscription to deploy the identity resources to, sourced from the variable `subscription_id_identity`.
# `subscription_id_connectivity`: The subscription ID of the subscription to deploy the connectivity resources to, sourced from the variable `subscription_id_connectivity`.
# `subscription_id_management`: The subscription ID of the subscription to deploy the management resources to, sourced from the variable `subscription_id_management`.
---
management:
  automation_account_name: aa-${default_postfix}
  location: ${default_location}
  log_analytics_workspace_name: law-${default_postfix}
  resource_group_name: rg-management-${default_postfix}

management_groups:
  root: # `key`: the unique identifier for the management group within the Terraform Module this is used in the `parent` field to build the hierarchy
    id: root-${default_postfix} # `id`: the id the management group will be created with in Azure
    display_name: Intermediate Root # `display_name`: the name the management group will be created with in Azure
    parent: ${root_parent_management_group_id} # `parent`: for the root management group this should be the id of the tenant root management group or your chosen root management group
    base_archetype: root # `archetype`: the archetype to use for this management group
  landing-zones:
    id: landing-zones-${default_postfix}
    display_name: Landing Zones
    parent: root # Note that `parent` refers to the `key` of it's parent as opposed to the `id` which can be different
    base_archetype: landing_zones
  platform:
    id: platform-${default_postfix}
    display_name: Platform
    parent: root
    base_archetype: platform
  identity:
    id: identity-${default_postfix}
    display_name: Identity
    parent: platform
    base_archetype: identity
    subscriptions:
      - ${subscription_id_identity}
  connectivity:
    id: connectivity-${default_postfix}
    display_name: Connectivity
    parent: platform
    base_archetype: connectivity
    subscriptions:
      - ${subscription_id_connectivity}
  management:
    id: management-${default_postfix}
    display_name: Management
    parent: platform
    base_archetype: management
    subscriptions:
      - ${subscription_id_management}
  corp:
    id: corp-${default_postfix}
    display_name: Corp
    parent: landing-zones
    base_archetype: corp
  online:
    id: online-${default_postfix}
    display_name: Online
    parent: landing-zones
    base_archetype: online
  sandboxes:
    id: sandboxes-${default_postfix}
    display_name: Sandboxes
    parent: root
    base_archetype: sandboxes
  decommissioned:
    id: decommissioned-${default_postfix}
    display_name: Decommissioned
    parent: root
    base_archetype: decommissioned

connectivity:
  hub_networking: # `hubnetworking` module, add inputs as listed on the module registry where necessary.
    hub_virtual_networks:
      primary:
        name: vnet-hub-${default_postfix}
        resource_group_name: rg-connectivity-${default_postfix}
        location: ${default_location}
        address_space:
          - 10.0.0.0/16
        firewall:
          name: fw-hub-${default_postfix}
          sku_name: AZFW_VNet
          sku_tier: Standard
          subnet_address_prefix: 10.0.1.0/24
        virtual_network_gateway: # `vnet-gateway` module, add inputs as listed on the module registry where necessary.
          name: vgw-hub-${default_postfix}
          sku: VpnGw1
          type: Vpn
          subnet_address_prefix: 10.0.2.0/24
